version: "3.9"

services:
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mariadb
    networks:
      - study_mate

  backend:
    image: backend
    container_name: sm_backend
    build:
      context: ./backend/back-end
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - ./backend/back-end:/app
    networks:
      - study_mate

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - study_mate

  frontend:
    image: frontend
    container_name: sm_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
      - ./frontend/build:/frontend/dist
      - /frontend/node_modules
    tty: true
    stdin_open: true
    networks:
      - study_mate

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    volumes:
      - ./frontend/build:/var/www/frontend
      # - ./backend/static:/backend/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certificate.pem:/etc/nginx/certificate.pem
      - ./nginx/private.key:/etc/nginx/private.key
    depends_on:
      - backend
      - frontend
    networks:
      - study_mate

volumes:
  mariadb_data:

networks:
  study_mate:
    driver: bridge
